name         'gizmoguy-pkg'
version      '0.0.0'
source       'https://github.com/gizmoguy/puppet-pkg'
author       'gizmoguy'
license      'Apache License, Version 2.0'
summary      'TODO'
description  'TODO'
project_page 'https://github.com/gizmoguy/puppet-pkg'
